# Generated by Django 4.1.2 on 2022-10-19 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('cpp', 'C++')], default='py', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('solution', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('testcase_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=100000)),
                ('problem_id', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_code', models.CharField(max_length=20000)),
                ('result', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
    ]
