# Generated by Django 4.1.2 on 2026-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_shown',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
