# Generated by Django 4.0.6 on 2022-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='answer',
            field=models.CharField(default='0', max_length=100000),
            preserve_default=False,
        ),
    ]
