# Generated by Django 4.0.6 on 2022-10-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testcase_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='unit',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='answer',
            new_name='output',
        ),
    ]
