# Generated by Django 4.1.2 on 2022-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_unit_testcase_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(blank=True, default=1.5),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_passed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
