# Generated by Django 4.1.2 on 2022-10-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_is_superuser_account_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
