# Generated by Django 4.1.2 on 2022-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='token_expire',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
