# Generated by Django 4.1.2 on 2022-10-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_token_account_token_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=4, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=4, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
    ]
