# Generated by Django 4.1.2 on 2022-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_problemtopic_topicproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
