# Generated by Django 4.1.2 on 2022-12-04 14:11

import api.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_problem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.utility.uploadTopic),
        ),
    ]
