# Generated by Django 4.1.2 on 2023-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_topic_description_alter_topic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
