# Generated by Django 4.1.2 on 2023-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_collection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproblem',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='topiccollection',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
