# Generated by Django 4.1.2 on 2023-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_collectionproblem_order_topiccollection_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission_regex',
            field=models.CharField(blank=True, default='.*', max_length=1000, null=True),
        ),
    ]
