# Generated by Django 4.1.2 on 2023-06-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_topicaccountaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='topicproblem',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='topicproblem',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
