# Generated by Django 4.1.2 on 2023-06-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_account_id_problem_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
