# Generated by Django 4.1.2 on 2023-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_submission_max_score_submission_passed_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('testfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='testfile/')),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
    ]
