# Generated by Django 4.1.2 on 2023-11-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_problem_submission_regex'),
        ('api', '0024_submission_max_score_submission_passed_ratio_and_more'),
    ]

    operations = [
    ]
