# Generated by Django 4.1.2 on 2023-07-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_submission_max_score_submission_passed_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='testfile/')),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('testfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='api.resourcefile')),
            ],
        ),
    ]
