# Generated by Django 4.1.2 on 2023-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_submission_submission_output_submissionoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionoutput',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
