# Generated by Django 4.1.2 on 2023-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_resourcefile_testfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='resource/'),
        ),
    ]
