# Generated by Django 4.1.2 on 2023-11-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20231110_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTestcase',
            fields=[
                ('submission_testcase_id', models.AutoField(primary_key=True, serialize=False)),
                ('output', models.CharField(max_length=100000)),
                ('is_passed', models.BooleanField(blank=True, default=False)),
                ('runtime_status', models.CharField(max_length=10)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='api.submission')),
                ('testcase', models.ForeignKey(db_column='testcase_id', on_delete=django.db.models.deletion.CASCADE, to='api.testcase')),
            ],
        ),
    ]
