# Generated by Django 4.1.2 on 2023-09-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_submissionoutput_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_output',
        ),
    ]
