# Generated by Django 4.1.2 on 2023-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_resourcefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfile',
            name='resource',
        ),
        migrations.AddField(
            model_name='testfile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='testfile/'),
        ),
        migrations.DeleteModel(
            name='ResourceFile',
        ),
    ]
