# Generated by Django 4.1.2 on 2023-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_submissiontestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontestcase',
            name='output',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
