# Generated by Django 4.1.2 on 2023-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_submissiontestcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(max_length=15),
        ),
    ]
