# Generated by Django 4.1.2 on 2023-12-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_account_is_admin_remove_collection_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='runtime_status',
            field=models.CharField(default='OK', max_length=10),
            preserve_default=False,
        ),
    ]
