# Generated by Django 4.1.2 on 2023-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_problem_created_date_problem_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='python', max_length=15),
            preserve_default=False,
        ),
    ]
