# Generated by Django 4.1.2 on 2023-12-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_submissiontestcase_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontestcase',
            name='testcase',
            field=models.ForeignKey(db_column='testcase_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.testcase'),
            preserve_default=False,
        ),
    ]
