# Generated by Django 4.1.2 on 2023-12-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_testcase_depricated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='depricated',
            new_name='deprecated',
        ),
    ]
