# Generated by Django 4.1.2 on 2023-12-16 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_collection_created_date_collection_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
