# Generated by Django 4.1.2 on 2023-12-19 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_topic_created_date_topic_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic'),
        ),
    ]
