# Generated by Django 4.1.2 on 2023-12-25 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_group_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
