# Generated by Django 4.1.2 on 2023-12-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_groupmember_updated_date_group_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sharing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_manage_collections',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_manage_problems',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_manage_topics',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_view_collections',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_view_problems',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_view_topics',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='permission_view_topics_log',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='sharing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='sharing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='TopicGroupPermission',
            fields=[
                ('topic_group_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_manage_topics', models.BooleanField(blank=True, default=False)),
                ('permission_view_topics', models.BooleanField(blank=True, default=False)),
                ('permission_view_topics_log', models.BooleanField(blank=True, default=False)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemGroupPermission',
            fields=[
                ('problem_group_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_manage_problems', models.BooleanField(blank=True, default=False)),
                ('permission_view_problems', models.BooleanField(blank=True, default=False)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionGroupPermission',
            fields=[
                ('collection_group_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_manage_collections', models.BooleanField(blank=True, default=False)),
                ('permission_view_collections', models.BooleanField(blank=True, default=False)),
                ('collection', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
    ]
