# Generated by Django 4.1.2 on 2023-12-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_collection_sharing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(blank=True, default=21169482018841058607917871046905516796, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='best_submission_id',
            field=models.IntegerField(blank=True, default=149805424067452344256336652203968127971, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.IntegerField(blank=True, default=268667638844507429395683049205342878308, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectiongrouppermission',
            name='collection_group_permission_id',
            field=models.IntegerField(blank=True, default=109233292530947572577678851192443289212, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(blank=True, default=122445526515845715335481945122286027175, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_member_id',
            field=models.IntegerField(blank=True, default=166402800061360647258671358541528594815, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(blank=True, default=319367364084708849680820356972231050063, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problemgrouppermission',
            name='problem_group_permission_id',
            field=models.IntegerField(blank=True, default=287900638121684221482942373316315838568, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.IntegerField(blank=True, default=333913260807308465398586534607890822150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='submission_testcase_id',
            field=models.IntegerField(blank=True, default=60359747276246222989657681614453318391, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.IntegerField(blank=True, default=67781662549803771653563714324350833289, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(blank=True, default=277680624917405823307023916753225961537, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topicgrouppermission',
            name='topic_group_permission_id',
            field=models.IntegerField(blank=True, default=268422871249108757857865287128153578738, primary_key=True, serialize=False, unique=True),
        ),
    ]
