# Generated by Django 4.1.2 on 2023-12-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, default='4256b03cc08048ef9aa3c0348b3271ce', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='best_submission_id',
            field=models.CharField(blank=True, default='a6a17c8c118947ddbe19ead82fadcf13', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(blank=True, default='0826e62bc2eb485bac000c5a6874354e', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectiongrouppermission',
            name='collection_group_permission_id',
            field=models.CharField(blank=True, default='99f216a4857a47bebf46585de5ba10b4', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(blank=True, default='cc530cb9f1ee4852b1eecd54edbc1ca0', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_member_id',
            field=models.CharField(blank=True, default='4a87ce6643ea4e46ba7a5949f80a9bfe', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, default='b8f79eec56bd42a78a993888721d2966', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problemgrouppermission',
            name='problem_group_permission_id',
            field=models.CharField(blank=True, default='d91f4c61dda94f2b93728feccb8441d5', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(blank=True, default='c494a2d002af4c439c258553ab41fd32', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='submission_testcase_id',
            field=models.CharField(blank=True, default='092f2c6cd8004cd68f8ae138b65d6c8e', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(blank=True, default='2f39f938182542d6b7d5df70a4c275a2', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(blank=True, default='9c5390db0ce942ac9562ec3422222b32', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topicgrouppermission',
            name='topic_group_permission_id',
            field=models.CharField(blank=True, default='35981bc9854a45dd9456f4958332466b', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
