# Generated by Django 4.1.2 on 2023-12-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, default='fe492e8f6bbd4df3b7d8518d66cc4141', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='best_submission_id',
            field=models.CharField(blank=True, default='fb2ee51251b144e0980aaaab7de3e2ed', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(blank=True, default='f70ffe44bd84425480ea4c73cc1eccf3', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectiongrouppermission',
            name='collection_group_permission_id',
            field=models.CharField(blank=True, default='e32d76e246844cf1834c711ac1d9f2c3', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionproblem',
            name='id',
            field=models.CharField(blank=True, default='9df47ab61f73413da2667553854563a7', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(blank=True, default='eeb90b4a7ee046e1be3e26967ed815b6', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_member_id',
            field=models.CharField(blank=True, default='b046b347361a4e839828ff8dc64fbf1c', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, default='9926855227344794b60bf52d107012c7', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='problemgrouppermission',
            name='problem_group_permission_id',
            field=models.CharField(blank=True, default='b5eeb3a47121426e930587793bfe173f', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(blank=True, default='bafecc07aa194ca8a292f387c21af764', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='submission_testcase_id',
            field=models.CharField(blank=True, default='0188a3eb130c480d95504eae32e1b912', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(blank=True, default='e47da5f04bdf4b599a6d59d439508e22', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(blank=True, default='9d84e241dd0643479412cac53c408657', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='id',
            field=models.CharField(blank=True, default='823d76779a1d4455aa3437ae7157fde3', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topicgrouppermission',
            name='topic_group_permission_id',
            field=models.CharField(blank=True, default='9ade2833620640cda259dbc40d3638ac', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
