# Generated by Django 4.1.2 on 2023-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, default='c61cc4ec15424865814d8403791fe7de', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='best_submission_id',
            field=models.CharField(blank=True, default='5de4232945d34426a0b7dc51c1671cbc', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(blank=True, default='c178f001e1e5408fa42263289589c1ae', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectiongrouppermission',
            name='collection_group_permission_id',
            field=models.CharField(blank=True, default='f504bf60f7d3421389bd8f939dd49caf', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collectionproblem',
            name='id',
            field=models.CharField(blank=True, default='2a36719d3b224b62ad031c94da0d253d', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(blank=True, default='497e3357fd344fe5bdd31788c211f5e7', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_member_id',
            field=models.CharField(blank=True, default='9fe857f7c4bf41aca173f07320779da4', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, default='1851825ec238474dabb80d4a03a05d2d', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemgrouppermission',
            name='problem_group_permission_id',
            field=models.CharField(blank=True, default='8adfff7ea11645d88a5b97cb56979165', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(blank=True, default='0ec695421ff341e086c9a37a662be3e1', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='submission_testcase_id',
            field=models.CharField(blank=True, default='9bbd6f2b00234676b0b661e74768a830', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(blank=True, default='81fd1d215c6e41a5b5d99608ab580c7b', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(blank=True, default='950c695bdef043c0b52e79bda497423e', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topiccollection',
            name='id',
            field=models.CharField(blank=True, default='0ddc6a8372ef4db59adf00aa24b39429', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topicgrouppermission',
            name='topic_group_permission_id',
            field=models.CharField(blank=True, default='8fdc25dc2fcf40588e76e71c1bed234b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
