# Generated by Django 4.1.2 on 2024-01-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allowed_languages',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
