# Generated by Django 4.1.2 on 2024-01-20 08:24

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_problem_allowed_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='VisitedLog',
            fields=[
                ('visited_log_id', models.CharField(blank=True, default=api.models.generate_uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('collection', models.ForeignKey(db_column='collection_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
                ('problem', models.ForeignKey(db_column='problem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('topic', models.ForeignKey(db_column='topic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
        ),
    ]
