# Generated by Django 4.1.2 on 2024-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdf_url',
            field=models.FileField(blank=True, default=None, null=True, upload_to='import-pdf/'),
        ),
    ]
